#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa o editor da base de dados
PYTHONPATH="ptracks/"
/usr/bin/env python -OO -m ptracks.dbEdit "$@" 2> ./dbEdit.$HOST.log
