#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa a aplicação
PYTHONPATH="ptracks/"
/usr/bin/env python -OO -m ptracks.newton "$@" > ./newton.$HOST.log 2>&1
